apiVersion: v1
kind: Service
metadata:
    name: "test-fb5f"
    labels:
        app: "test-fb5f"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "test-fb5f"